name: impactsuite_flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  drift: ^2.22.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  sqlite3_flutter_libs: ^0.5.26
  file_picker: ^8.1.4
  archive: ^3.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
